table FactTransaction
	lineageTag: 27836ee3-b556-44cf-8c18-efd09f1d9741

	measure 'Total Transactions' = COUNTROWS(FactTransaction)
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: fb3537a3-7f7c-4774-86fa-8c637520aa52

	measure 'Total Transaction Value' = SUM(FactTransaction[Amount])
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 1fe93d05-4033-4fdb-b07e-232b574ab4b1

	measure 'Total Fees' = SUM(FactTransaction[Total Fee])
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 6ef18cab-2eaf-446d-9c33-dbd4b3f8ed8e

	measure 'Average Transaction Value' = DIVIDE([Total Transaction Value], [Total Transactions])
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: f4948acb-0b85-45bd-917b-046d0eb4e54f

	measure 'Average Fee' = DIVIDE([Total Fees], [Total Transactions])
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: 1f5db2e6-a4c9-46d8-a5a5-1e2661d3eb69

	measure 'Active Customers' = DISTINCTCOUNT(FactTransaction[CustomerID])
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 145b59bb-e463-4f6c-90c9-f56aea043dfe

	measure 'Transactions per Customer' = DIVIDE([Total Transactions], [Active Customers])
		formatString: #,##0.0
		displayFolder: Core KPIs
		lineageTag: 71ba7ef3-7d20-4d17-8cd8-6d3148dcc73b

	measure 'Average Customer Score' = AVERAGE(FactTransaction[CustomerScore])
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 7b270412-f766-42ce-9446-c20f1e1d172a

	measure 'Credit Card Fees' = SUM(FactTransaction[CreditCardFees])
		formatString: #,##0
		displayFolder: Fee Breakdown
		lineageTag: 805701a4-f9ff-4b4a-9cb2-6b3359aa9626

	measure 'Insurance Fees' = SUM(FactTransaction[InsuranceFees])
		formatString: #,##0
		displayFolder: Fee Breakdown
		lineageTag: db0a592f-02ab-42d9-952f-25052d9ae1d9

	measure 'Late Payment Amount' = SUM(FactTransaction[LatePaymentAmount])
		formatString: #,##0
		displayFolder: Fee Breakdown
		lineageTag: b3d191ad-3d5e-424a-9a42-e229749ed971

	measure 'Total Transaction Value PM' = CALCULATE([Total Transaction Value], DATEADD(DimDate[Date], -1, MONTH))
		formatString: #,##0
		isHidden
		displayFolder: Time Intelligence\Helpers
		lineageTag: 92ea071a-e4af-43ad-9412-035222e1547f

	measure 'Total Transaction Value PY' = CALCULATE([Total Transaction Value], SAMEPERIODLASTYEAR(DimDate[Date]))
		formatString: #,##0
		isHidden
		displayFolder: Time Intelligence\Helpers
		lineageTag: 94a5dfaa-23b8-43de-b37a-d608f53dcd20

	measure 'Transactions PM' = CALCULATE([Total Transactions], DATEADD(DimDate[Date], -1, MONTH))
		formatString: #,##0
		isHidden
		displayFolder: Time Intelligence\Helpers
		lineageTag: 11697fd6-e27a-4705-b535-2fe36c0ef24b

	measure 'MoM Growth %' = DIVIDE([Total Transaction Value] - [Total Transaction Value PM], [Total Transaction Value PM])
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: fdfce7c3-feea-44e3-944a-caad1db78eb0

	measure 'YoY Growth %' = DIVIDE([Total Transaction Value] - [Total Transaction Value PY], [Total Transaction Value PY])
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: d4730ef0-5d48-4b17-942a-85a9ca5f0b52

	measure 'Transaction Growth %' = DIVIDE([Total Transactions] - [Transactions PM], [Transactions PM])
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: a4fa1522-7bef-47be-8851-8d3191c66228

	measure 'Fee Rate %' = DIVIDE([Total Fees], [Total Transaction Value])
		formatString: 0.00%
		displayFolder: Analytical %
		lineageTag: 21bd7b0f-5d19-42f1-96e9-f43690de4208

	measure 'Fee Contribution %' = DIVIDE([Total Fees], CALCULATE([Total Fees], ALLSELECTED(FactTransaction)))
		formatString: 0.0%
		displayFolder: Analytical %
		lineageTag: 4aa9b66c-17d1-4c0e-a036-ebe5c367977d

	measure 'Transaction Share %' = DIVIDE([Total Transactions], CALCULATE([Total Transactions], ALLSELECTED(FactTransaction)))
		formatString: 0.0%
		displayFolder: Analytical %
		lineageTag: 78980550-4509-4b9b-b03d-493abc290ba9

	measure 'Offer Alignment Rate %' = AVERAGE(FactTransaction[OfferAligned])
		formatString: 0.0%
		displayFolder: Analytical %
		lineageTag: 01a241eb-1b00-41a1-a001-3f7d16a48816

	measure 'Most Used Channel' = VAR t = TOPN(1, VALUES(FactTransaction[Channel]), CALCULATE([Total Transactions]), DESC) RETURN CONCATENATEX(t, FactTransaction[Channel])
		formatString: General
		displayFolder: Convenience
		lineageTag: 6577ba23-19e7-47a3-9753-3dd7026a0f33

	measure 'Most Valuable Transaction Type' = VAR t = TOPN(1, VALUES(FactTransaction[TransactionType]), CALCULATE([Total Transaction Value]), DESC) RETURN CONCATENATEX(t, FactTransaction[TransactionType])
		formatString: General
		displayFolder: Convenience
		lineageTag: 9e220f5e-a65b-4b8c-8887-efa102930fb1

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: df383908-c2b2-4444-8f44-9d3e12565653
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column TransactionDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f1b7a07-e3a1-44cb-9852-6609a6f5c14c
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

	column TransactionType
		dataType: string
		lineageTag: efe8b738-c6ae-4fcc-990b-a519b7b3ad29
		summarizeBy: none
		sourceColumn: TransactionType

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: e70f1dda-0273-48fd-9344-8ffbe9f44dae
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductCategory
		dataType: string
		lineageTag: 7ac55204-f8ac-453a-834f-1516f3c6ad4a
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

	column ProductSubcategory
		dataType: string
		lineageTag: 387fe490-fefd-41b9-a328-9a9e3662c13f
		summarizeBy: none
		sourceColumn: ProductSubcategory

		annotation SummarizationSetBy = Automatic

	column BranchCity
		dataType: string
		lineageTag: d830a478-0c04-4c58-adff-1a666244e0fe
		summarizeBy: none
		sourceColumn: BranchCity

		annotation SummarizationSetBy = Automatic

	column BranchLat
		dataType: double
		lineageTag: 8e550201-b342-4ddb-8b2b-57210fc89f8e
		summarizeBy: sum
		sourceColumn: BranchLat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BranchLong
		dataType: double
		lineageTag: dc84d876-3d17-4da0-a5ef-712de8fb663e
		summarizeBy: sum
		sourceColumn: BranchLong

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Channel
		dataType: string
		lineageTag: f18e6511-9864-475c-bb3d-4cd2136f3c61
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 43e2d28e-b296-41da-ad56-e6a28b1c5b8b
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column CreditCardFees
		dataType: double
		lineageTag: 2b327f68-58ba-4d57-ad89-111b37c9af10
		summarizeBy: sum
		sourceColumn: CreditCardFees

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InsuranceFees
		dataType: double
		lineageTag: 2ebefd56-629b-4f72-b8b2-abada9cd9dff
		summarizeBy: sum
		sourceColumn: InsuranceFees

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LatePaymentAmount
		dataType: double
		lineageTag: 70cc474f-cbf4-45f1-90d6-c97db209cfcf
		summarizeBy: sum
		sourceColumn: LatePaymentAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerScore
		dataType: int64
		formatString: 0
		lineageTag: 4a15d634-923c-4dfa-9f2e-6743371d7dfd
		summarizeBy: sum
		sourceColumn: CustomerScore

		annotation SummarizationSetBy = Automatic

	column MonthlyIncome
		dataType: double
		lineageTag: d8740684-4c00-49ce-84ac-94b15a06d43d
		summarizeBy: sum
		sourceColumn: MonthlyIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerSegment
		dataType: string
		lineageTag: fc2fe37c-4987-48d6-8485-12d89043cd1f
		summarizeBy: none
		sourceColumn: CustomerSegment

		annotation SummarizationSetBy = Automatic

	column RecommendedOffer
		dataType: string
		lineageTag: 3e350f7c-9768-4f02-ae57-ee92311c0f78
		summarizeBy: none
		sourceColumn: RecommendedOffer

		annotation SummarizationSetBy = Automatic

	column 'Total Fee'
		dataType: double
		lineageTag: 29508ad9-0af2-4cd0-b7e9-6ea6efde5388
		summarizeBy: sum
		sourceColumn: Total Fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CreditScoreGroup = SWITCH(TRUE(), FactTransaction[CustomerScore] < 580, "Poor", FactTransaction[CustomerScore] < 670, "Fair", FactTransaction[CustomerScore] < 740, "Good", FactTransaction[CustomerScore] < 800, "Very Good", "Excellent")
		dataType: string
		lineageTag: e2f5e8b2-d863-4c2e-8956-c32b086457e0

	column OfferExpectedCategory = RELATED(MapOfferCategory[ExpectedCategory])
		dataType: string
		lineageTag: 6bf4aad3-6547-4dee-b0b3-9dbbc1daff0d

	column OfferAligned = IF(FactTransaction[ProductCategory] = FactTransaction[OfferExpectedCategory], 1, 0)
		dataType: int64
		lineageTag: d8dcd5ff-fe58-4d5d-b53c-d8930cf90697

	partition FactTransaction = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Downloads\Banking_Transactional_Dataset_Cleaned.xlsx"), null, true),
				    Banking_Transactions_Table = Source{[Item="Banking_Transactions",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Banking_Transactions_Table,{{"TransactionID", Int64.Type}, {"CustomerID", Int64.Type}, {"TransactionDate", type datetime}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"Quarter", Int64.Type}, {"YearMonth", type date}, {"TransactionType", type text}, {"Amount", type number}, {"ProductCategory", type text}, {"ProductSubcategory", type text}, {"BranchCity", type text}, {"BranchLat", type number}, {"BranchLong", type number}, {"Channel", type text}, {"Currency", type text}, {"CreditCardFees", type number}, {"InsuranceFees", type number}, {"LatePaymentAmount", type number}, {"CustomerScore", Int64.Type}, {"MonthlyIncome", type number}, {"CustomerSegment", type text}, {"RecommendedOffer", type text}, {"Total Fee", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"TransactionID", "Year", "Month", "MonthName", "Quarter", "YearMonth"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

